gitlab:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.alshin.xyz'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.alshin.xyz:30080'
      gitlab_rails['gitlab_shell_ssh_port'] = 30022
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '30080:30080'
    - '30443:443'
    - '30022:22'
  volumes:
    - '/root/gitlab/config:/etc/gitlab'
    - '/root/gitlab/logs:/var/log/gitlab'
    - '/root/gitlab/data:/var/opt/gitlab'
