version: '3.1'
services: 
  adminer: 
    image: clue/adminer 
    ports:
      - 8088:80
    volumes:
      - ./db-data:/var/lib/mysql:rw
  # dbPostgres: 
  #   image: postgres:10
  #   ports: 
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: mydb
  dbMysql: 
    image: mysql:5.6
    ports:  
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - ./db-data:/var/lib/mysql:rw
  # dbMongo: 
  #   image: mongo:3.6.2
  #   ports:
  #     - 27017:27017
  #   environment: 
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: changeme
  # dbRedis:
  #   image: redis
  #   ports:
  #     - 6379:6379
