version: "3"
services:
  node:
    image: "keymetrics/pm2:latest-alpine"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
    command: ["pm2-dev", "start", "process.yml"]
    max-size: "1g"
    ports:
      - 8081:1080
